/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoamigopresentacion;

import Utilerias.utileriaHeaderSidebar;
import Utilerias.utileriasBotones;
import com.mycompany.motoamigodto.NuevoPaqueteDTO;
import com.mycompany.motoamigodto.PaqueteDTO;
import com.mycompany.motoamigodto.ProductoDTO;
import com.mycompany.motoamigodto.ProductosPaqueteDTO;
import Paquete.CrearPaquete;
import Paquete.ICrearPaquete;
import Paquete.PaqueteException;
import enums.TamañoPaqueteDTO;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author joset
 */
public class FrmCrearPaquete extends JFrame {

    private final ICrearPaquete cuCrearPaquete;
    private final List<ProductosPaqueteDTO> productosAgregados;

    /**
     * Crea una nueva instancia del formulario.
     */
    public FrmCrearPaquete() {
        this.cuCrearPaquete = new CrearPaquete();
        this.productosAgregados = new ArrayList<>();
        initComponents();
        configurarTabla();
        setLocationRelativeTo(null);
        setTitle("MotoAmigo - Crear Paquete");
        utileriaHeaderSidebar.aplicarHeader(jPanel1);
        configurarTamanios();
        estilarComponentes();
        actualizarTotales();
    }

    /**
     * Carga los tamaños disponibles en el combo.
     */
    private void configurarTamanios() {
        cmbTamanio.removeAllItems();
        cmbTamanio.addItem("Selecciona un tamaño");
        for (TamañoPaqueteDTO t : TamañoPaqueteDTO.values()) {
            cmbTamanio.addItem(t.name());
        }
    }

    /**
     * Aplica los estilos visuales a los componentes.
     */
    private void estilarComponentes() {
        utileriasBotones.panelRedondeado(panelTarjeta, Color.WHITE, 18);
        utileriasBotones.panelRedondeado(panelPesoCalc, new Color(255, 245, 235), 16);
        utileriasBotones.panelRedondeado(panelPrecioCalc, new Color(232, 246, 232), 16);
        utileriasBotones.btnRedondeado(btnGuardar, "negro", 16);
        utileriasBotones.btnRedondeado(btnCancelar, "blanco", 16);
        utileriasBotones.btnRedondeado(btnAgregarProducto, "naranja", 14);
        utileriasBotones.btnRedondeado(btnQuitarProducto, "blanco", 14);

        Font fontBoton = new Font("Segoe UI", Font.BOLD, 16);
        btnGuardar.setFont(fontBoton);
        btnCancelar.setFont(fontBoton);
        btnCancelar.setForeground(new Color(60, 60, 60));
        btnQuitarProducto.setForeground(new Color(220, 53, 69));
        btnQuitarProducto.setBackground(new Color(253, 237, 240));
    }

    /**
     * Recalcula y muestra el peso total y precio total del paquete.
     */
    private void actualizarTotales() {
        float pesoTotal = 0f;
        float precioTotal = 0f;
        for (ProductosPaqueteDTO pp : productosAgregados) {
            pesoTotal += pp.getPesoTotal();
            if (pp.getProducto() != null) {
                precioTotal += pp.getProducto().getPrecio() * pp.getCantidad();
            }
        }
        lblPesoCalculado.setText(String.format("%.2f kg", pesoTotal));
        lblPrecioCalculado.setText(String.format("$%.2f", precioTotal));
    }

    /**
     * Refresca la tabla con los productos agregados al paquete.
     */
    private void refrescarTablaProductos() {
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
        for (ProductosPaqueteDTO productoPaquete : productosAgregados) {
            String nombre = productoPaquete.getProducto() != null ? productoPaquete.getProducto().getNombre() : "Sin producto";
            modelo.addRow(new Object[]{
                nombre,
                String.format("%.2f $",(productoPaquete.getProducto().getPrecio() * productoPaquete.getCantidad())),
                String.format("%.2f kg", productoPaquete.getPesoTotal()),
                productoPaquete.getCantidad()
            });
        }
        actualizarTotales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTarjeta = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblTamanio = new javax.swing.JLabel();
        cmbTamanio = new javax.swing.JComboBox();
        lblImagen = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        panelPesoCalc = new javax.swing.JPanel();
        lblPesoTitulo = new javax.swing.JLabel();
        lblPesoCalculado = new javax.swing.JLabel();
        panelPrecioCalc = new javax.swing.JPanel();
        lblPrecioTitulo = new javax.swing.JLabel();
        lblPrecioCalculado = new javax.swing.JLabel();
        lblProductosTitulo = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnQuitarProducto = new javax.swing.JButton();
        scrollProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotoAmigo - Crear Paquete");
        setMaximumSize(new java.awt.Dimension(990, 660));
        setMinimumSize(new java.awt.Dimension(990, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTarjeta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setText("Crear Paquete");
        lblTitulo.setForeground(new java.awt.Color(51, 55, 69));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        panelTarjeta.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 30));

        lblDescripcion.setText("Define los datos del nuevo paquete.");
        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        panelTarjeta.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 56, 400, 20));

        lblNombre.setText("NOMBRE");
        lblNombre.setForeground(new java.awt.Color(115, 128, 135));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelTarjeta.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 18));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        panelTarjeta.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 114, 460, 32));

        lblTamanio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTamanio.setForeground(new java.awt.Color(115, 128, 135));
        lblTamanio.setText("TAMAÑO");
        panelTarjeta.add(lblTamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 120, 18));

        cmbTamanio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        panelTarjeta.add(cmbTamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 114, 450, 32));

        lblImagen.setText("IMAGEN (URL)");
        lblImagen.setForeground(new java.awt.Color(115, 128, 135));
        lblImagen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelTarjeta.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 161, 140, 18));

        txtImagen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        panelTarjeta.add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, 930, 32));

        panelPesoCalc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPesoTitulo.setText("PESO CALCULADO");
        lblPesoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        panelPesoCalc.add(lblPesoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 150, 18));

        lblPesoCalculado.setText("0.00 kg");
        lblPesoCalculado.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        panelPesoCalc.add(lblPesoCalculado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 36, 150, 35));

        panelTarjeta.add(panelPesoCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 237, 220, 85));

        panelPrecioCalc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecioTitulo.setText("PRECIO CALCULADO");
        lblPrecioTitulo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        panelPrecioCalc.add(lblPrecioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 160, 18));

        lblPrecioCalculado.setText("$0.00");
        lblPrecioCalculado.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        panelPrecioCalc.add(lblPrecioCalculado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 36, 150, 35));

        panelTarjeta.add(panelPrecioCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 237, 220, 85));

        lblProductosTitulo.setText("PRODUCTOS DEL PAQUETE");
        lblProductosTitulo.setForeground(new java.awt.Color(115, 128, 135));
        lblProductosTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelTarjeta.add(lblProductosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 342, 220, 18));

        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAgregarProducto.setText("+ Agregar producto");
        btnAgregarProducto.setBorderPainted(false);
        btnAgregarProducto.setFocusPainted(false);
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        panelTarjeta.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 190, 35));

        btnQuitarProducto.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnQuitarProducto.setText("Quitar seleccionado");
        btnQuitarProducto.setBorderPainted(false);
        btnQuitarProducto.setFocusPainted(false);
        btnQuitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProductoActionPerformed(evt);
            }
        });
        panelTarjeta.add(btnQuitarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 190, 35));

        tblProductos.setRowHeight(28);
        scrollProductos.setViewportView(tblProductos);

        panelTarjeta.add(scrollProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 379, 930, 120));

        btnCancelar.setText("Cancelar");
        btnCancelar.setForeground(new java.awt.Color(96, 96, 96));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelTarjeta.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 515, 200, 50));

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGuardar.setText("Guardar paquete");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelTarjeta.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 280, 50));

        jPanel1.add(panelTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 990, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cmbTamanio.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un tamaño.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        TamañoPaqueteDTO tamanio = TamañoPaqueteDTO.valueOf((String) cmbTamanio.getSelectedItem());
        float precio = 0f;
        for (ProductosPaqueteDTO pp : productosAgregados) {
            if (pp.getProducto() != null) {
                precio += pp.getProducto().getPrecio() * pp.getCantidad();
            }
        }

        NuevoPaqueteDTO nuevo = new NuevoPaqueteDTO(
                txtNombre.getText().trim(),
                tamanio,
                productosAgregados,
                precio,
                null,
                null
        );

        PaqueteDTO creado;
        try {
            creado = cuCrearPaquete.crear(nuevo);
            if (creado != null) {
                JOptionPane.showMessageDialog(this, "Paquete creado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "El módulo de negocio aún no está implementado.\nLa información se mantiene en pantalla.",
                        "Pendiente", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (PaqueteException ex) {

        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        DlgBuscarProductos dlgBuscarProductos = new DlgBuscarProductos(this, true);
        dlgBuscarProductos.setVisible(true);

        ProductoDTO productoSeleccionado = dlgBuscarProductos.getProductoSeleccionado();

        if (productoSeleccionado == null) {
            return;
        }

        int cantidad = solicitarCantidadProducto();

        if (cantidad <= 0) {
            return;
        }

        float pesoTotal = productoSeleccionado.getPeso() * cantidad;

        ProductosPaqueteDTO productoPaquete = new ProductosPaqueteDTO(
                productoSeleccionado,
                cantidad,
                pesoTotal
        );

        productosAgregados.add(productoPaquete);
        refrescarTablaProductos();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"Nombre", "Total", "Peso total","Cantidad"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblProductos.setModel(modelo);
    }
    private int solicitarCantidadProducto() {
        String cantidadTexto = JOptionPane.showInputDialog(
                this,
                "Ingresa la cantidad del producto:",
                "Cantidad",
                JOptionPane.QUESTION_MESSAGE
        );

        if (cantidadTexto == null) {
            return 0;
        }

        cantidadTexto = cantidadTexto.trim();

        if (cantidadTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "La cantidad es obligatoria.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            return 0;
        }

        try {
            int cantidad = Integer.parseInt(cantidadTexto);

            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "La cantidad debe ser mayor a 0.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                return 0;
            }

            return cantidad;

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "La cantidad debe ser un número entero válido.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            return 0;
        }
    }
    private void btnQuitarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarProductoActionPerformed
        int fila = tblProductos.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto de la tabla para quitarlo.",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int filaModelo = tblProductos.convertRowIndexToModel(fila);

        productosAgregados.remove(filaModelo);
        refrescarTablaProductos();
    }//GEN-LAST:event_btnQuitarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JComboBox cmbTamanio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPesoCalculado;
    private javax.swing.JLabel lblPesoTitulo;
    private javax.swing.JLabel lblPrecioCalculado;
    private javax.swing.JLabel lblPrecioTitulo;
    private javax.swing.JLabel lblProductosTitulo;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelPesoCalc;
    private javax.swing.JPanel panelPrecioCalc;
    private javax.swing.JPanel panelTarjeta;
    private javax.swing.JScrollPane scrollProductos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
