/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoamigopresentacion;

import Utilerias.utileriasBotones;
import Utilerias.utileriasMensajes;
import com.mycompany.motoamigodto.IncidenteDTO;
import com.mycompany.motoamigonegocio.Observers.EventoEntrega;
import com.mycompany.motoamigonegocio.Observers.GestorNotificacionesEntrega;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Rectangle;
import static javax.swing.BorderFactory.createCompoundBorder;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import panelesUtilerias.PanelHeader;

/**
 *
 * @author Dell
 */
public class FrmFormularioIncidenteRepartidor extends javax.swing.JFrame {

    private String incidenteSeleccionado = null;
    private FrmSeguimientoTiempoRealRepartidor frmMapa;
    private javax.swing.JTextArea txtDescripcionOtro;
    private javax.swing.JScrollPane scrollOtro;

    public FrmFormularioIncidenteRepartidor(FrmSeguimientoTiempoRealRepartidor frmMapa) {
        this.frmMapa = frmMapa;
        initComponents();
        inicializarUI();
        setLocationRelativeTo(null);

    }

    private void inicializarUI() {
        panPrincipal.add(new PanelHeader(), new AbsoluteConstraints(0, 0, 1366, 130));
        utileriasBotones.btnRedondeado(btnPaqueteDañado, "blanco", 30);
        utileriasBotones.btnRedondeado(btnPaqueteExtravido, "blanco", 30);
        utileriasBotones.btnRedondeado(btnAccidenteAveria, "blanco", 30);
        utileriasBotones.btnRedondeado(btnClienteNoDisponible, "blanco", 30);
        utileriasBotones.btnRedondeado(btnOtro, "blanco", 30);
        utileriasBotones.btnRedondeado(btnConfirmar, "negro", 30);

        txtDescripcionOtro = new JTextArea();
        txtDescripcionOtro.setRows(4);
        txtDescripcionOtro.setLineWrap(true);
        txtDescripcionOtro.setWrapStyleWord(true);
        txtDescripcionOtro.setFont(new Font("Segoe UI", 0, 13));
        txtDescripcionOtro.setBorder(createCompoundBorder(new LineBorder(new java.awt.Color(232, 234, 240), 1, true), new EmptyBorder(8, 12, 8, 12)));

        scrollOtro = new JScrollPane(txtDescripcionOtro);
        scrollOtro.setBorder(null);
        scrollOtro.setVisible(false);

        panCentral.add(scrollOtro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        panCentral = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        lblReportarProblema = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnPaqueteDañado = new javax.swing.JButton();
        btnPaqueteExtravido = new javax.swing.JButton();
        btnClienteNoDisponible = new javax.swing.JButton();
        btnAccidenteAveria = new javax.swing.JButton();
        btnOtro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incidente");
        setMinimumSize(new java.awt.Dimension(1008, 738));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panCentral.setBackground(new java.awt.Color(255, 255, 255));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(102, 102, 102));
        btnCancelar.setText("X   Cancelar Reporte");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblReportarProblema.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblReportarProblema.setText("Reportar un problema");

        lblDescripcion.setText("Seleccione el incidente que ocurrio durante la entrega.");

        btnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar Reporte");
        btnConfirmar.setOpaque(true);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnPaqueteDañado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPaqueteDañado.setText("Paquete dañado");
        btnPaqueteDañado.setHideActionText(true);
        btnPaqueteDañado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPaqueteDañado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPaqueteDañado.setOpaque(true);
        btnPaqueteDañado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaqueteDañadoActionPerformed(evt);
            }
        });

        btnPaqueteExtravido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPaqueteExtravido.setText("Paquete extraviado");
        btnPaqueteExtravido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPaqueteExtravido.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPaqueteExtravido.setOpaque(true);
        btnPaqueteExtravido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaqueteExtravidoActionPerformed(evt);
            }
        });

        btnClienteNoDisponible.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClienteNoDisponible.setText("Cliente no disponible");
        btnClienteNoDisponible.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClienteNoDisponible.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnClienteNoDisponible.setOpaque(true);
        btnClienteNoDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteNoDisponibleActionPerformed(evt);
            }
        });

        btnAccidenteAveria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAccidenteAveria.setText("Accidente o Avería");
        btnAccidenteAveria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAccidenteAveria.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAccidenteAveria.setOpaque(true);
        btnAccidenteAveria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccidenteAveriaActionPerformed(evt);
            }
        });

        btnOtro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOtro.setText("Otro");
        btnOtro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOtro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnOtro.setOpaque(true);
        btnOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCentralLayout = new javax.swing.GroupLayout(panCentral);
        panCentral.setLayout(panCentralLayout);
        panCentralLayout.setHorizontalGroup(
            panCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCentralLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDescripcion)
                    .addComponent(lblReportarProblema)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteNoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPaqueteExtravido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPaqueteDañado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                    .addComponent(btnAccidenteAveria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOtro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panCentralLayout.setVerticalGroup(
            panCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCentralLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(lblReportarProblema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion)
                .addGap(18, 18, 18)
                .addComponent(btnPaqueteDañado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPaqueteExtravido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClienteNoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAccidenteAveria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        panPrincipal.add(panCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1030, 680));

        getContentPane().add(panPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1010, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        frmMapa.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPaqueteDañadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteDañadoActionPerformed
        incidenteSeleccionado = "paquete_dañado";
        marcarSeleccionado(btnPaqueteDañado);
    }//GEN-LAST:event_btnPaqueteDañadoActionPerformed

    private void btnPaqueteExtravidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteExtravidoActionPerformed
        incidenteSeleccionado = "paquete_extraviado";
        marcarSeleccionado(btnPaqueteExtravido);
    }//GEN-LAST:event_btnPaqueteExtravidoActionPerformed

    private void btnClienteNoDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteNoDisponibleActionPerformed
        incidenteSeleccionado = "cliente_no_disponible";
        marcarSeleccionado(btnClienteNoDisponible);
    }//GEN-LAST:event_btnClienteNoDisponibleActionPerformed

    private void btnAccidenteAveriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccidenteAveriaActionPerformed
        incidenteSeleccionado = "accidente_averia";
        marcarSeleccionado(btnAccidenteAveria);
    }//GEN-LAST:event_btnAccidenteAveriaActionPerformed

    private void btnOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtroActionPerformed
        incidenteSeleccionado = "otro";
        marcarSeleccionado(btnOtro);
        boolean visible = !scrollOtro.isVisible();
        scrollOtro.setVisible(visible);

        if (visible) {
            Rectangle rect = btnOtro.getBounds();
            scrollOtro.setBounds(rect.x, rect.y + rect.height + 8, rect.width, 100);
            txtDescripcionOtro.requestFocus();
        }

        panCentral.revalidate();
        panCentral.repaint();
    }//GEN-LAST:event_btnOtroActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (incidenteSeleccionado == null) {
            JOptionPane.showMessageDialog(this,
                    "Por favor selecciona un incidente.",
                    "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String titulo, descripcion;

        switch (incidenteSeleccionado) {
            case "paquete_dañado" -> {
                titulo = "No Completada";
                descripcion = "El paquete debe ser devuelto al emprendedor. La entrega se marcará como no completada.";
            }
            case "paquete_extraviado" -> {
                titulo = "Incidente - En Revisión";
                descripcion = "Soporte se pondrá en contacto contigo para ayudarte con el paquete.";
            }
            case "cliente_no_disponible" -> {
                titulo = "No Completada - Cliente no disponible";
                descripcion = "Debes devolver el paquete. El viaje será pagado de todos modos.";
            }
            case "accidente_averia" -> {
                titulo = "Disponible (Re-publicada)";
                descripcion = "Otro repartidor recogerá el paquete. Por favor espera al repartidor.";
            }
            case "otro" -> {
                String desc = txtDescripcionOtro.getText().trim();
                if (desc.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Por favor describe el incidente.",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                titulo = "Incidente Reportado";
                descripcion = "Tu reporte: \"" + desc + "\" ha sido enviado correctamente.";
            }
            default -> {
                titulo = "Incidente Reportado";
                descripcion = "Tu reporte ha sido enviado correctamente.";
            }
        }
        GestorNotificacionesEntrega.getInstance().notificar(
                EventoEntrega.PEDIDO_NO_COMPLETADO,
                new IncidenteDTO(incidenteSeleccionado, descripcion)
        );

        utileriasMensajes.mostrarAlertaIncidente(
                (Frame) SwingUtilities.getWindowAncestor(this),
                titulo,
                descripcion,
                () -> {
                    frmMapa.setVisible(true);
                    dispose();
                }
        );

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void marcarSeleccionado(JButton btnActivo) {
        JButton[] todos = {
            btnPaqueteDañado, btnPaqueteExtravido, btnClienteNoDisponible,
            btnAccidenteAveria, btnOtro
        };
        for (JButton b : todos) {
            utileriasBotones.btnRedondeado(b, "blanco", 30);
        }
        utileriasBotones.btnRedondeadoSeleccionado(btnActivo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccidenteAveria;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClienteNoDisponible;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnOtro;
    private javax.swing.JButton btnPaqueteDañado;
    private javax.swing.JButton btnPaqueteExtravido;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblReportarProblema;
    private javax.swing.JPanel panCentral;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
