
package com.mycompany.motoamigopresentacion;

import Utilerias.utileriaHeaderSidebar;
import Utilerias.utileriasBotones;
import com.mycompany.motoamigodto.PaqueteDTO;
import com.mycompany.motoamigopresentacion.controladores.ControlNavegacionEmprendedor;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;

/**
 * Frame del menú de paquetes del emprendedor. Muestra una tarjeta con los
 * accesos al CRUD de paquetes (Editar, Agregar, Eliminar, Historial) y el botón
 * Buscar. La navegación entre menús principales se delega al
 * ControlNavegacionEmprendedor.
 *
 * @author joset
 */
public class FrmMenuPaquetes extends JFrame {

    private FrmCrearPaquete frmCrear;
    private FrmEditarPaquete frmEditar;
    private FrmEliminarPaquete frmEliminar;
    private FrmHistorialPaquetes frmHistorial;
    private DlgBuscarPaquetes dlgBuscarPaquetes;

    /**
     * Crea una nueva instancia del menú de paquetes.
     */
    public FrmMenuPaquetes() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("MotoAmigo - Paquetes");
        utileriaHeaderSidebar.aplicarHeaderYSidebar(jPanel1, "PAQUETES");
        ControlNavegacionEmprendedor.getInstancia().registrarMenuActivo(this);
        estilarBotones();

    }

    /**
     * Aplica el estilo redondeado a los botones del menú.
     *
     */
    private void estilarBotones() {
        utileriasBotones.btnRedondeado(btnEditar, "blanco", 16);
        utileriasBotones.btnRedondeado(btnAgregar, "negro", 16);
        utileriasBotones.btnRedondeado(btnEliminar, "blanco", 16);
        utileriasBotones.btnRedondeado(btnHistorial, "blanco", 16);
        utileriasBotones.panelRedondeado(panelTarjeta, Color.WHITE, 18);

        Font fontBoton = new Font("Segoe UI", Font.BOLD, 18);
        btnEditar.setFont(fontBoton);
        btnAgregar.setFont(fontBoton);
        btnEliminar.setFont(fontBoton);
        btnHistorial.setFont(fontBoton);

        btnAgregar.setForeground(Color.WHITE);
        btnEditar.setForeground(new Color(232, 100, 10));
        btnEliminar.setForeground(new Color(220, 53, 69));
        btnHistorial.setForeground(new Color(60, 60, 60));

        btnEliminar.setBackground(new Color(253, 237, 240));
        btnHistorial.setBackground(new Color(245, 245, 245));
        btnEditar.setBackground(new Color(255, 245, 235));
    }

    /**
     * Cierra la sub-pantalla que esté abierta. Se invoca antes de abrir una
     * nueva sub-pantalla para mantener la regla de mutua exclusión entre
     * sub-pantallas.
     */
    private void cerrarSubPantallaActiva() {
        if (frmCrear != null) {
            frmCrear.dispose();
            frmCrear = null;
        }
        if (frmEditar != null) {
            frmEditar.dispose();
            frmEditar = null;
        }
        if (frmEliminar != null) {
            frmEliminar.dispose();
            frmEliminar = null;
        }
        if (frmHistorial != null) {
            frmHistorial.dispose();
            frmHistorial = null;
        }
        if (dlgBuscarPaquetes != null) {
            dlgBuscarPaquetes.dispose();
            dlgBuscarPaquetes = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTarjeta = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 740));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        panelTarjeta.setMaximumSize(new java.awt.Dimension(860, 660));
        panelTarjeta.setMinimumSize(new java.awt.Dimension(860, 660));
        panelTarjeta.setPreferredSize(new java.awt.Dimension(860, 660));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(33, 37, 45));
        lblTitulo.setText("Paquetes");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(108, 117, 125));
        lblDescripcion.setText("Administra los paquetes de tu negocio.");

        btnEditar.setBackground(new java.awt.Color(255, 245, 235));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(232, 100, 10));
        btnEditar.setText("  Editar paquete");
        btnEditar.setBorderPainted(false);
        btnEditar.setFocusPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar paquete");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setFocusPainted(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(253, 237, 240));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(220, 53, 69));
        btnEliminar.setText("Eliminar paquete");
        btnEliminar.setToolTipText("");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnHistorial.setBackground(new java.awt.Color(245, 245, 245));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(60, 60, 60));
        btnHistorial.setText("Historial");
        btnHistorial.setBorderPainted(false);
        btnHistorial.setFocusPainted(false);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTarjetaLayout = new javax.swing.GroupLayout(panelTarjeta);
        panelTarjeta.setLayout(panelTarjetaLayout);
        panelTarjetaLayout.setHorizontalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitulo)
                        .addComponent(lblDescripcion))
                    .addGroup(panelTarjetaLayout.createSequentialGroup()
                        .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        panelTarjetaLayout.setVerticalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion)
                .addGap(35, 35, 35)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(376, Short.MAX_VALUE))
        );

        jPanel1.add(panelTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 860, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        cerrarSubPantallaActiva();
        dlgBuscarPaquetes = new DlgBuscarPaquetes(this, true);
        dlgBuscarPaquetes.setVisible(true);
        PaqueteDTO paqueteSeleccionado = dlgBuscarPaquetes.getPaqueteSeleccionado();

        if (paqueteSeleccionado == null) {
            return;
        }

        frmEditar = new FrmEditarPaquete(paqueteSeleccionado);
        frmEditar.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        cerrarSubPantallaActiva();
        frmCrear = new FrmCrearPaquete();
        frmCrear.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        cerrarSubPantallaActiva();
        dlgBuscarPaquetes = new DlgBuscarPaquetes(this, true);
        dlgBuscarPaquetes.setVisible(true);

        PaqueteDTO paqueteSeleccionado = dlgBuscarPaquetes.getPaqueteSeleccionado();

        if (paqueteSeleccionado == null) {
            return;
        }

        frmEliminar = new FrmEliminarPaquete(paqueteSeleccionado);
        frmEliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        cerrarSubPantallaActiva();
        frmHistorial = new FrmHistorialPaquetes();
        frmHistorial.setVisible(true);
    }//GEN-LAST:event_btnHistorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelTarjeta;
    // End of variables declaration//GEN-END:variables
}
