
package com.mycompany.motoamigopresentacion;

import Utilerias.utileriaHeaderSidebar;
import Utilerias.utileriasBotones;
import com.mycompany.motoamigodto.ProductoDTO;
import com.mycompany.motoamigopresentacion.controladores.ControlNavegacionEmprendedor;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;

/**
 *
 * @author joset
 */
public class FrmMenuProductos extends JFrame {

    private FrmCrearProducto frmCrear;
    private FrmEditarProducto frmEditar;
    private FrmEliminarProducto frmEliminar;
    private DlgBuscarProductos dlgBuscar;

    /**
     * Crea una nueva instancia del menú de productos.
     */
    public FrmMenuProductos() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("MotoAmigo - Productos");
        utileriaHeaderSidebar.aplicarHeaderYSidebar(jPanel1, "PRODUCTOS");
        ControlNavegacionEmprendedor.getInstancia().registrarMenuActivo(this);
        estilarBotones();
    }

    /**
     * Aplica el estilo redondeado a los botones del menú.
     */
    private void estilarBotones() {
        utileriasBotones.btnRedondeado(btnEliminar, "blanco", 16);
        utileriasBotones.btnRedondeado(btnEditar, "blanco", 16);
        utileriasBotones.btnRedondeado(btnCrear, "negro", 16);
        utileriasBotones.panelRedondeado(panelTarjeta, Color.WHITE, 18);


        Font fontBoton = new Font("Segoe UI", Font.BOLD, 18);
        btnEliminar.setFont(fontBoton);
        btnEditar.setFont(fontBoton);
        btnCrear.setFont(fontBoton);

        btnCrear.setForeground(Color.WHITE);
        btnEditar.setForeground(new Color(232, 100, 10));
        btnEliminar.setForeground(new Color(220, 53, 69));
        
        btnEliminar.setBackground(new Color(253,237,240));
        btnEditar.setBackground(new Color(255, 245, 235));
    }

    /**
     * Cierra la sub-pantalla que esté abierta. Se invoca antes de abrir una
     * nueva sub-pantalla para mantener la regla de mutua exclusión entre
     * sub-pantallas.
     */
    private void cerrarSubPantallaActiva() {
        if (frmCrear != null) {
            frmCrear.dispose();
            frmCrear = null;
        }
        if (frmEditar != null) {
            frmEditar.dispose();
            frmEditar = null;
        }
        if (frmEliminar != null) {
            frmEliminar.dispose();
            frmEliminar = null;
        }
        if (dlgBuscar != null) {
            dlgBuscar.dispose();
            dlgBuscar = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTarjeta = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1008, 738));
        setMinimumSize(new java.awt.Dimension(1008, 738));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        panelTarjeta.setMaximumSize(new java.awt.Dimension(860, 660));
        panelTarjeta.setMinimumSize(new java.awt.Dimension(860, 660));
        panelTarjeta.setPreferredSize(new java.awt.Dimension(860, 660));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(33, 37, 45));
        lblTitulo.setText("Productos");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(108, 117, 125));
        lblDescripcion.setText("Administra los productos de tu negocio.");

        btnEliminar.setBackground(new java.awt.Color(253, 237, 240));
        btnEliminar.setForeground(new java.awt.Color(220, 53, 69));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 245, 235));
        btnEditar.setForeground(new java.awt.Color(232, 100, 10));
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.setFocusPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCrear.setBackground(new java.awt.Color(0, 0, 0));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear producto");
        btnCrear.setBorderPainted(false);
        btnCrear.setFocusPainted(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTarjetaLayout = new javax.swing.GroupLayout(panelTarjeta);
        panelTarjeta.setLayout(panelTarjetaLayout);
        panelTarjetaLayout.setHorizontalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblDescripcion)
                    .addGroup(panelTarjetaLayout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        panelTarjetaLayout.setVerticalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion)
                .addGap(35, 35, 35)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        jPanel1.add(panelTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 850, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        cerrarSubPantallaActiva();
        
        dlgBuscar = new DlgBuscarProductos(this, true);
        dlgBuscar.setVisible(true);

        ProductoDTO productoSeleccionado = dlgBuscar.getProductoSeleccionado();

        if (productoSeleccionado == null) {
            return;
        }

        frmEliminar = new FrmEliminarProducto(productoSeleccionado);
        frmEliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        cerrarSubPantallaActiva();
        
        dlgBuscar = new DlgBuscarProductos(this, true);
        dlgBuscar.setVisible(true);

        ProductoDTO productoSeleccionado = dlgBuscar.getProductoSeleccionado();

        if (productoSeleccionado == null) {
            return;
        }

        frmEditar = new FrmEditarProducto(productoSeleccionado);
        frmEditar.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        cerrarSubPantallaActiva();
        frmCrear = new FrmCrearProducto();
        frmCrear.setVisible(true);
    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelTarjeta;
    // End of variables declaration//GEN-END:variables
}
