/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.repartidorespresentacion;

import Utilerias.utileriasBotones;
import com.mycompany.motoamigodto.RepartidorDTO;
import com.mycompany.motoamigodto.SolicitudEntregaDTO;
import com.mycompany.motoamigonegocio.Observers.EventoEntrega;
import com.mycompany.motoamigonegocio.Observers.GestorNotificacionesEntrega;
import com.mycompany.motoamigonegocio.Observers.INotificacionPedido;
import com.mycompany.motoamigopresentacion.controladores.ControlMenuPrincipal;
import com.mycompany.motoamigopresentacion.controladores.SesionActiva;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jesus Omar
 */
public class FrmMenuPrincipalRepartidor extends javax.swing.JFrame implements INotificacionPedido {

    /**
     * Creates new form FrmMenuPrincipalRepartidor
     */
    public FrmMenuPrincipalRepartidor() {
        initComponents();
        iniciarUI();
        GestorNotificacionesEntrega.getInstance().agregarObserver(this);
        setLocationRelativeTo(null);
    }

    private void iniciarUI() {
        jScrollPane1.setBorder(null);
        pnlListaEnvios.setBorder(null);
        utileriasBotones.panelRedondeado(panelRepartidor, new Color(29, 38, 59), 30);
        panelRepartidor.setPanel(this.pnlListaEnvios);

        RepartidorDTO repartidor = SesionActiva.getInstancia().getRepartidor();
        panelRepartidor.cargarDatosRepartidor(repartidor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuInferior = new javax.swing.JPanel();
        pnlCentral = new javax.swing.JPanel();
        panelRepartidor = new panelesUtilerias.panelRepartidor();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlListaEnvios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1008, 738));
        setResizable(false);

        pnlMenuInferior.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlMenuInferiorLayout = new javax.swing.GroupLayout(pnlMenuInferior);
        pnlMenuInferior.setLayout(pnlMenuInferiorLayout);
        pnlMenuInferiorLayout.setHorizontalGroup(
            pnlMenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        pnlMenuInferiorLayout.setVerticalGroup(
            pnlMenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnlMenuInferior, java.awt.BorderLayout.PAGE_END);

        pnlCentral.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCentral.setLayout(new javax.swing.BoxLayout(pnlCentral, javax.swing.BoxLayout.Y_AXIS));

        panelRepartidor.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCentral.add(panelRepartidor);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlListaEnvios.setBackground(new java.awt.Color(255, 255, 255));
        pnlListaEnvios.setMinimumSize(new java.awt.Dimension(100, 100));
        pnlListaEnvios.setLayout(new javax.swing.BoxLayout(pnlListaEnvios, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlListaEnvios);

        pnlCentral.add(jScrollPane1);

        getContentPane().add(pnlCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void actualizar(String evento, Object datos) {
        if (!EventoEntrega.PEDIDO_DISPONIBLE.name().equals(evento)
                || !(datos instanceof SolicitudEntregaDTO solicitud)) {
            return;
        }

        SwingUtilities.invokeLater(() -> {
            JOptionPane.showMessageDialog(this,
                    "Nueva solicitud disponible para repartir.",
                    "Pedido disponible",
                    JOptionPane.INFORMATION_MESSAGE);
            new FrmPublicarPedidoRepartidor(solicitud).setVisible(true);
        });
    }

    @Override
    public void dispose() {
        GestorNotificacionesEntrega.getInstance().eliminarObserver(this);
        super.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private panelesUtilerias.panelRepartidor panelRepartidor;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlListaEnvios;
    private javax.swing.JPanel pnlMenuInferior;
    // End of variables declaration//GEN-END:variables
}
