/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoamigopresentacion;

import Utilerias.utileriasBotones;
import com.mycompany.motoamigodto.EmprendedorDTO;
import com.mycompany.motoamigopresentacion.controladores.ControlMenuPrincipal;
import java.awt.Color;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import panelesUtilerias.PanelHeader;

/**
 *
 * @author Jesus Omar
 */
public class FrmMenuPrincipalEmprendedor extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipalEmprendedor() {
        initComponents();
        setLocationRelativeTo(null);
        iniciarUI();
        jPanel1.add(new PanelHeader(), new AbsoluteConstraints(0, 0, 1366, 130));
    }

    private void iniciarUI(){
        // Formato de los componentes del frame
        utileriasBotones.panelRedondeado(pnlNuevoEnvio, new Color(232, 100, 10), 30);
        utileriasBotones.btnRedondeado(btnNuevoEnvio, "blanco", 30);
        jScrollPane1.setBorder(null);
        pnlEnvios.setBorder(null);
        // Cargar datos del emprendedor
        EmprendedorDTO e = ControlMenuPrincipal.getInstance().buscarEmprendedorPorId(2L);
        lblEmprendedor.setText("¡Hola, "+e.getNombre()+"!");
        // Cargar entregas del emprendedor
        ControlMenuPrincipal.getInstance().cargarEntregas(this.pnlEnvios, 2L, "emprendedor");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlNuevoEnvio = new javax.swing.JPanel();
        lblEmprendedor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoEnvio = new javax.swing.JButton();
        lblEnviosActivos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlEnvios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1010, 680));

        lblEmprendedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmprendedor.setForeground(new java.awt.Color(255, 255, 255));
        lblEmprendedor.setText("¡Hola, Emprendedor!");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Qué enviamos hoy?");

        btnNuevoEnvio.setForeground(new java.awt.Color(232, 100, 10));
        btnNuevoEnvio.setText("Nuevo Envio");
        btnNuevoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuevoEnvioLayout = new javax.swing.GroupLayout(pnlNuevoEnvio);
        pnlNuevoEnvio.setLayout(pnlNuevoEnvioLayout);
        pnlNuevoEnvioLayout.setHorizontalGroup(
            pnlNuevoEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEnvioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlNuevoEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmprendedor)
                    .addComponent(jLabel1)
                    .addComponent(btnNuevoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlNuevoEnvioLayout.setVerticalGroup(
            pnlNuevoEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEnvioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblEmprendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnNuevoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        lblEnviosActivos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnviosActivos.setText("Envíos Activos");

        jScrollPane1.setBorder(null);

        pnlEnvios.setLayout(new javax.swing.BoxLayout(pnlEnvios, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlEnvios);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEnviosActivos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlNuevoEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnlNuevoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEnviosActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel1.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEnvioActionPerformed
        ControlMenuPrincipal.getInstance().abrirPantallaEnvioEmpr();
    }//GEN-LAST:event_btnNuevoEnvioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoEnvio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmprendedor;
    private javax.swing.JLabel lblEnviosActivos;
    private javax.swing.JPanel pnlEnvios;
    private javax.swing.JPanel pnlNuevoEnvio;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
