/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesUtilerias;

import Utilerias.utileriasBotones;
import com.mycompany.motoamigodto.EntregaDTO;
import com.mycompany.motoamigopresentacion.controladores.ControlMenuPrincipal;
import com.mycompany.motoamigopresentacion.controladores.SesionActiva;
import java.awt.Color;

/**
 *
 * @author Jesus Omar
 */
public class PanelTarjetaPedido extends javax.swing.JPanel {

    private EntregaDTO entrega;

    /**
     * Creates new form PanelTarjetaPedido
     */
    public PanelTarjetaPedido() {
        initComponents();
        utileriasBotones.btnRedondeado(btnVerPedido, "naranja", 30);
        utileriasBotones.panelRedondeado(this, new Color(248, 249, 250), 30);
    }
   
    public void cargarDatosEnTarjeta(EntregaDTO entrega) {
        this.entrega = entrega;

        lblDireccionOrigen.setText(entrega.getDireccionOrigen());
        lblDireccionDestino.setText("→ " + entrega.getDireccionDestino());

        lblPrecio.setText("$" + String.format("%.2f", entrega.getCosto()));
        lblDistancia.setText(String.format("%.1f km", entrega.getDistancia()));

        if (SesionActiva.getInstancia().esEmprendedor()) {
            String estado = entrega.getEstadoEntrega();
            if ("EN_CAMINO".equals(estado) || "ACEPTADA".equals(estado)) {
                btnVerPedido.setText("Rastrear pedido");
            } else if ("ENTREGADA".equals(estado) || "FINALIZADA".equals(estado)) {
                btnVerPedido.setVisible(false);
            } else {
                btnVerPedido.setText("Ver pedido");
            }
        }

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDireccionOrigen = new javax.swing.JLabel();
        lblDireccionDestino = new javax.swing.JLabel();
        btnVerPedido = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        lblDistancia = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 116));

        lblDireccionOrigen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDireccionOrigen.setForeground(new java.awt.Color(17, 24, 39));
        lblDireccionOrigen.setText("Direccion Origen");

        lblDireccionDestino.setForeground(new java.awt.Color(75, 85, 99));
        lblDireccionDestino.setText("→ Direccion Destino");

        btnVerPedido.setText("Ver pedido");
        btnVerPedido.setOpaque(true);
        btnVerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPedidoActionPerformed(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(249, 115, 22));
        lblPrecio.setText("$0.00");
        lblPrecio.setMaximumSize(new java.awt.Dimension(360, 200));

        lblDistancia.setForeground(new java.awt.Color(75, 85, 99));
        lblDistancia.setText("0.0 km");
        lblDistancia.setMaximumSize(new java.awt.Dimension(350, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccionDestino)
                            .addComponent(lblDireccionOrigen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionOrigen)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionDestino)
                    .addComponent(lblDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidoActionPerformed
        if (entrega == null) {
            return;
        }

        if (SesionActiva.getInstancia().esEmprendedor()) {
            String estado = entrega.getEstadoEntrega();
            if ("EN_CAMINO".equals(estado) || "ACEPTADA".equals(estado)) {
                ControlMenuPrincipal.getInstance().continuarPedido(entrega);
            } else {
                ControlMenuPrincipal.getInstance().mostrarDetallePedidoEmprendedor(entrega);
            }
            return;
        }
        String estado = entrega.getEstadoEntrega();
        if ("EN_CAMINO".equals(estado) || "ACEPTADA".equals(estado)) {
            ControlMenuPrincipal.getInstance().continuarPedido(entrega);
        } else {
            ControlMenuPrincipal.getInstance().mostrarDetallePedido(entrega);
        }
    }//GEN-LAST:event_btnVerPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerPedido;
    private javax.swing.JLabel lblDireccionDestino;
    private javax.swing.JLabel lblDireccionOrigen;
    private javax.swing.JLabel lblDistancia;
    private javax.swing.JLabel lblPrecio;
    // End of variables declaration//GEN-END:variables
}
