/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesUtilerias;

import Utilerias.utileriasBotones;
import com.mycompany.motoamigodto.RepartidorDTO;
import com.mycompany.motoamigopresentacion.controladores.ControlMenuPrincipal;
import com.mycompany.motoamigopresentacion.controladores.SesionActiva;
import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.JPanel;

/**
 *
 * @author Jesus Omar
 * Esta clase crea la tarjeta donde el repartidor ve su nombre y 
 * puede activar y desactivar su conexion
 */
public class panelRepartidor extends javax.swing.JPanel {

    private JPanel panelDestino;
    
    /**
     * Creates new form panelRepartidor
     */
    public panelRepartidor() {
        initComponents();
        utileriasBotones.hacerBotonToggleCircular(btnConexion, 30);
    }

    public void cargarDatosRepartidor(RepartidorDTO repartidor){
        this.lblRepartidor.setText(repartidor.getNombre());
    }
    
    public void setPanel(JPanel panel){
        this.panelDestino = panel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRepartidor = new javax.swing.JLabel();
        lblConexion = new javax.swing.JLabel();
        btnConexion = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(32767, 90));
        setMinimumSize(new java.awt.Dimension(900, 90));

        lblRepartidor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRepartidor.setForeground(new java.awt.Color(255, 255, 255));
        lblRepartidor.setText("Repartidor");

        lblConexion.setForeground(new java.awt.Color(156, 163, 175));
        lblConexion.setText("Desconectado");

        btnConexion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnConexionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRepartidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 743, Short.MAX_VALUE)
                        .addComponent(btnConexion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConexion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConexion)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConexionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnConexionItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            lblConexion.setText("Conectado");
            lblConexion.setForeground(Color.GREEN);
            String idRepartidor = SesionActiva.getInstancia().getIdRepartidor();
            if (idRepartidor == null) {
                return;
            }
            ControlMenuPrincipal.getInstance().cargarEntregasRepartidor(panelDestino, idRepartidor);
        }else{
            lblConexion.setText("Desconectado");
            lblConexion.setForeground(new Color(156,163,175));
            if(panelDestino != null){
                panelDestino.removeAll();
                panelDestino.revalidate();
                panelDestino.repaint();
            }
        }
    }//GEN-LAST:event_btnConexionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConexion;
    private javax.swing.JLabel lblConexion;
    private javax.swing.JLabel lblRepartidor;
    // End of variables declaration//GEN-END:variables
}
