/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminPresentacion;

import javax.swing.JButton;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import panelesUtilerias.PanelHeader;

/**
 *
 * @author calo2
 */
public class MenuAdminFORM extends javax.swing.JFrame {

    private final ControlCUBloqueos control;

    /**
     * Creates new form MenuAdminFORM
     */
    public MenuAdminFORM() {
        initComponents();
        control = new ControlCUBloqueos();

        control.inicializarMenuAdmin(this);
    }

    public JButton getBtnBloquearRepartidor() {
        return btnBloquearRepartidor;
    }

    public JButton getBtnDesbloqueoMasivo() {
        return btnDesbloqueoMasivo;
    }

    public JButton getBtnHistorialBloqueos() {
        return btnHistorialBloqueos;
    }

    public JButton getBtnHistorialDesbloqueos() {
        return btnHistorialDesbloqueos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBloquearRepartidor = new javax.swing.JButton();
        btnDesbloqueoMasivo = new javax.swing.JButton();
        btnHistorialBloqueos = new javax.swing.JButton();
        btnHistorialDesbloqueos = new javax.swing.JButton();
        btnCatalogoEmprendedores = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Administrador");

        btnBloquearRepartidor.setBackground(new java.awt.Color(255, 102, 0));
        btnBloquearRepartidor.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        btnBloquearRepartidor.setForeground(new java.awt.Color(255, 255, 255));
        btnBloquearRepartidor.setText("Bloquear Repartidor");
        btnBloquearRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearRepartidorActionPerformed(evt);
            }
        });

        btnDesbloqueoMasivo.setBackground(new java.awt.Color(255, 102, 0));
        btnDesbloqueoMasivo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        btnDesbloqueoMasivo.setForeground(new java.awt.Color(255, 255, 255));
        btnDesbloqueoMasivo.setText("Desbloqueo Masivo");
        btnDesbloqueoMasivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloqueoMasivoActionPerformed(evt);
            }
        });

        btnHistorialBloqueos.setBackground(new java.awt.Color(255, 102, 0));
        btnHistorialBloqueos.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        btnHistorialBloqueos.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialBloqueos.setText("Historial de bloqueos");
        btnHistorialBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialBloqueosActionPerformed(evt);
            }
        });

        btnHistorialDesbloqueos.setBackground(new java.awt.Color(255, 102, 0));
        btnHistorialDesbloqueos.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        btnHistorialDesbloqueos.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialDesbloqueos.setText("Historial de desbloqueos");
        btnHistorialDesbloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialDesbloqueosActionPerformed(evt);
            }
        });

        btnCatalogoEmprendedores.setBackground(new java.awt.Color(255, 102, 0));
        btnCatalogoEmprendedores.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        btnCatalogoEmprendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnCatalogoEmprendedores.setText("Catalogo emprendedores");
        btnCatalogoEmprendedores.setMaximumSize(new java.awt.Dimension(248, 31));
        btnCatalogoEmprendedores.setMinimumSize(new java.awt.Dimension(248, 31));
        btnCatalogoEmprendedores.setPreferredSize(new java.awt.Dimension(248, 31));
        btnCatalogoEmprendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatalogoEmprendedoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnHistorialBloqueos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                    .addComponent(btnBloquearRepartidor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(71, 71, 71)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDesbloqueoMasivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHistorialDesbloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)))))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(btnCatalogoEmprendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBloquearRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesbloqueoMasivo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistorialBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorialDesbloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnCatalogoEmprendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(1008, 80));
        jPanel3.setPreferredSize(new java.awt.Dimension(1008, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MotoAmigo");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Admin");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBloquearRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearRepartidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBloquearRepartidorActionPerformed

    private void btnDesbloqueoMasivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloqueoMasivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesbloqueoMasivoActionPerformed

    private void btnHistorialBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialBloqueosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialBloqueosActionPerformed

    private void btnHistorialDesbloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialDesbloqueosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialDesbloqueosActionPerformed

    private void btnCatalogoEmprendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatalogoEmprendedoresMouseClicked
        new CatalogoEmprendedoresFORM().setVisible(true);
    }//GEN-LAST:event_btnCatalogoEmprendedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdminFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBloquearRepartidor;
    private javax.swing.JButton btnCatalogoEmprendedores;
    private javax.swing.JButton btnDesbloqueoMasivo;
    private javax.swing.JButton btnHistorialBloqueos;
    private javax.swing.JButton btnHistorialDesbloqueos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
