
package com.mycompany.emprendedorpresentacion;

import Utilerias.utileriaHeaderSidebar;
import Utilerias.utileriasBotones;
import com.mycompany.emprendedoresdto.EmprendedorDTO;
import com.mycompany.motoamigopresentacion.controladores.ControlMenuPrincipal;
import com.mycompany.motoamigopresentacion.controladores.ControlNavegacionEmprendedor;
import com.mycompany.motoamigopresentacion.controladores.SesionActiva;
import java.awt.Color;

/**
 *
 * @author Jesus Omar
 */
public class FrmMenuPrincipalEmprendedor extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipalEmprendedor() {
        initComponents();
        
        ControlNavegacionEmprendedor.getInstancia().registrarMenuActivo(this);
        setLocationRelativeTo(null);
        iniciarUI();
        utileriaHeaderSidebar.aplicarHeaderYSidebar(jPanel1, "INICIO");
    }

    private void iniciarUI(){
        utileriasBotones.panelRedondeado(pnlNuevoEnvio, new Color(232, 100, 10), 30);
        utileriasBotones.btnRedondeado(btnNuevoEnvio, "blanco", 30);
        jScrollPane1.setBorder(null);
        pnlEnvios.setBorder(null);
        String idEmprendedor = SesionActiva.getInstancia().getIdEmprendedor();
        ControlMenuPrincipal.getInstance().cargarEntregasEmprendedor(this.pnlEnvios,idEmprendedor, "emprendedor");
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlNuevoEnvio = new javax.swing.JPanel();
        lblEmprendedor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoEnvio = new javax.swing.JButton();
        lblEnviosActivos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlEnvios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Emprendedor");
        setMinimumSize(new java.awt.Dimension(1020, 740));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(860, 660));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(860, 660));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(860, 660));

        pnlNuevoEnvio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmprendedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmprendedor.setForeground(new java.awt.Color(255, 255, 255));
        lblEmprendedor.setText("¡Hola, Emprendedor!");
        pnlNuevoEnvio.add(lblEmprendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 19, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Qué enviamos hoy?");
        pnlNuevoEnvio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, -1, -1));

        btnNuevoEnvio.setForeground(new java.awt.Color(232, 100, 10));
        btnNuevoEnvio.setText("Nuevo Envio");
        btnNuevoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEnvioActionPerformed(evt);
            }
        });
        pnlNuevoEnvio.add(btnNuevoEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, 800, 35));

        lblEnviosActivos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnviosActivos.setText("Envíos Activos");

        jScrollPane1.setBorder(null);

        pnlEnvios.setLayout(new javax.swing.BoxLayout(pnlEnvios, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlEnvios);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblEnviosActivos))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlNuevoEnvio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnlNuevoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblEnviosActivos)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 840, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEnvioActionPerformed
        ControlMenuPrincipal.getInstance().abrirPantallaEnvioEmpr();
    }//GEN-LAST:event_btnNuevoEnvioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoEnvio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmprendedor;
    private javax.swing.JLabel lblEnviosActivos;
    private javax.swing.JPanel pnlEnvios;
    private javax.swing.JPanel pnlNuevoEnvio;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
